# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WithUs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WithUs
pod 'SwiftLint'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
end
