# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'ChatAppMessenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatAppMessenger

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Lint
pod 'SwiftLint'

# Facebook
pod 'FBSDKLoginKit'

end
